name: artifact example

on: [push]

env:
  USER_NAME: Sahil 

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v2
          with:
            name: ${{ env.USER_NAME }}
            path: ./file.txt

            